### ISSUE TITLE
01.08 Overscan doesn't tell users where to get files

### ISSUE THREAD

**Issue by JuanCab** [mwcraig/ccd-reduction-and-photometry-guide#17]
Probably due to some reorganization in the past, there users are asked to process python_imred_data files that don't exist. I found a link in the 02.01 notebook that said 

`The data for this example can be downloaded from [http://www.stsci.edu/~etollerud/python_imred_data.tar](http://www.stsci.edu/~etollerud/python_imred_data.tar)`

I suggest adding this link right above that cell in the notebook.

**Comment by mwcraig** [comment]
Fixed, see https://github.com/mwcraig/ccd-reduction-and-photometry-guide/blob/master/notebooks/00-00-Preface.ipynb
