### ISSUE TITLE
02.01 Quite a few grammatical errors and missing data

### ISSUE THREAD

**Issue by JuanCab** [mwcraig/ccd-reduction-and-photometry-guide#20]
There are quite a few grammatical errors in this notebook but most importantly it ends with "Example 2: No overscan subtraction, but trim the images" but there is no link to the data provided.

**Comment by mwcraig** [comment]
Grammar is still bad, but data is at  https://github.com/mwcraig/ccd-reduction-and-photometry-guide/blob/master/notebooks/00-00-Preface.ipynb
