### ISSUE TITLE
03.02 Link to Palomar data is broken and reduced dark frame not apparently available

### ISSUE THREAD

**Issue by JuanCab** [mwcraig/ccd-reduction-and-photometry-guide#22]
When first loading the Palomar data, if we want to be consistent with previous notebooks, we should use

`calibrated_images = Path('./python_imred_data')`

not

`calibrated_images = Path('./')`

as it currently is.  However, even with that, the reduced dark file doesn't appear to be exist there.

Assuming this file is downloadable, include a link, if not, if it was supposed to be produced in a previous notebook, link to that notebook.

**Comment by mwcraig** [comment]
Please see https://github.com/mwcraig/ccd-reduction-and-photometry-guide/blob/master/notebooks/00-00-Preface.ipynb
