### ISSUE TITLE
03.03 Couldn't test since it refers to a file in your directory

### ISSUE THREAD

**Issue by JuanCab** [mwcraig/ccd-reduction-and-photometry-guide#23]
The call to 

ccd = CCDData.read('/Users/mattcraig/Desktop/2018-07-23-reduced/kelt-16-S001-R001-C110-r.fit')

is likely to work only on Matt Craig's laptop... I have a copy of the file if we need to make it publicly available.

**Comment by mwcraig** [comment]
I *think* all of this has been fixed by providing download links in https://github.com/mwcraig/ccd-reduction-and-photometry-guide/blob/master/notebooks/00-00-Preface.ipynb
