### ISSUE TITLE
03.05 Comments incorrect in calibrating dark frames

### ISSUE THREAD

**Issue by JuanCab** [mwcraig/ccd-reduction-and-photometry-guide#24]
When calibrating the dark frames from Palomar you have the code state:

```
for ccd, file_name in ex1_darks_raw.ccds(imagetyp='DARK',            # Just get the bias frames
                                         ccd_kwargs={'unit': 'adu'}, # CCDData requires a unit for the image if 
                                                                     # it is not in the header
                                         return_fname=True           # Provide the file name too.
                                        ):
```

The comments in the code should say you are getting just the DARK frames.

Also, what does showing the reduced frames after triming the overscan in the 'calibrating dark frames' loop supposed to show?  I think you need to reload the directory via:

`ex1_images_reduced = ImageFileCollection(ex1_path_reduced)`

otherwise you show the File Collection before the newly reduced data was added.

Couldn't do anything with the `example-thermo-electric` data because it isn't available.

**Comment by mwcraig** [comment]
Thanks, added a `refresh` to the `ImageFileCollection`
