### ISSUE TITLE
Copy edit notebooks, round 1

### ISSUE THREAD

**Issue by mwcraig** [mwcraig/ccd-reduction-and-photometry-guide#4]
These notebooks are ready for copy editing:
 + Notebook whose name starts "00"
+ All notebooks whose name starts with "01"

**Comment by kelle** [comment]
Matt, could you please add @lglattly to this repo and assign her to this issue. Thanks!

**Comment by mwcraig** [comment]
@kelle @lglattly -- assigned!

**Comment by mwcraig** [comment]
Closed by #5
